### PR TITLE
Use datasource for retrieving aws inspector rules packages

### PR DESCRIPTION
**Pull request by MattiasGees**
Now that there is a datasource for getting the rules packages arns, we can use that to retrieve the correct arns per region. You will still be able to override it, but we now have a sane default that can be used in every region.

This is tested for backwards compatibility as well.

### CODE REVIEW

**Comment by iuriaranda** [comment]
Isn't there a minimum version of terraform or the aws provider that we should enforce?

**Comment by MattiasGees** [comment]
@iuriaranda yes, but isn't that with every resource we use?

**Comment by iuriaranda** [comment]
@MattiasGees I mean that the data source that you use for this, is only available from a specific version of the aws provider, so I think we should enforce this in the module. (if possible)

**Comment by MattiasGees** [comment]
@iuriaranda but that holds for all resources. So that means we have to do it everywhere.

**Comment by SamClinckspoor** [comment]
doesn't terraform use latest unless you specify the version?

**Comment by iuriaranda** [comment]
@MattiasGees true, the difference is that, in this case, the data source is really recent, so it's entirely possible that not everyone will be using an up-to-date provider, and it could result in unexpected/unclear errors. So I think it's worth the effort to just enforce a minimum version.

@SamClinckspoor yes, but I think that only happens if you run `init` again.

**Comment by MattiasGees** [comment]
@iuriaranda but we did that for other things as well the last 3 years. So I don't see why all of a sudden this is an issue.

**Pull request merged**
